enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  '@sapphire/decorators@*':
    dependencies:
      '@sapphire/discord.js-utilities': ^4.9.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpEnableEsmLoader: false
