enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  '@sapphire/decorators@*':
    dependencies:
      '@sapphire/discord.js-utilities': ^4.9.4
  '@sapphire/framework@*':
    dependencies:
      '@discordjs/builders': ^0.15.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpEnableEsmLoader: false
